name: PDF Deploy

# Controls when the workflow will run
on: push

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    # Job runs only for tagged pushes 
    if: startsWith(github.ref, 'refs/tags/')
    
    # Adding permission to create the release
    permissions:
      contents: write

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Github Action for LaTeX
        uses: xu-cheng/latex-action@v2
        with:
          root_file: "template.tex"

      - name: Rename template file
        run: mv template.pdf curriculum.pdf
        
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: template.pdf
